Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -20,6 +20,11 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: read
+      packages: write
+      attestations: write
+      id-token: write
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - uses: actions/checkout@v5.0.0
@@ -51,7 +56,15 @@ jobs:
           sudo ./distrobuilder build-incus ./debian.yaml debian-output --vm
           ls -lR debian-output
           cd debian-output
-          docker run -v $PWD:/disk debian:bookworm sh -c '
-            apt-get update && apt-get install -y guestfs-tools && cd /disk && virt-get-kernel -a disk.qcow2
+          docker run -v $PWD:/disk debian:trixie sh -c '
+            set -ex
+            apt-get update
+            apt-get install -y guestfs-tools oras
+            cd /disk
+            virt-get-kernel -a disk.qcow2
+            mv vmlinuz* vmlinuz
+            mv initrd.img* initrd.img
+            echo "ghcr.io/${{ github.repository }}/image:${{ github.sha }}"
+            echo -n 'invalidpw' | oras login -u ${{ github.actor }} --password-stdin ghcr.io
+            oras push ghcr.io/${{ github.repository }}/image:${{ github.sha }}
           '
-          ls -lR
